// Generated by the Server.DBViewGenerator.  DO NOT EDIT!
using System;
using ETHotfix;
using MongoDB.Bson;
using Google.Protobuf.Collections;
using MongoDB.Bson.Serialization.Attributes;

namespace ETModel
{
}
